version: '3'
services:
    app:
        container_name: "minter_explorer_api"
        build: ./docker/php
        volumes:
            - ./source:/var/www
        depends_on:
            - postgres
            - redis
        links:
            - postgres
            - redis
    nginx:
        container_name: "minter_explorer_web_server"
        build: ./docker/nginx
        volumes:
            - ./source:/var/www
        ports:
            - "8000:80"
        links:
            - app
    postgres:
        container_name: "minter_explorer_db"
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: explorer_db
            POSTGRES_USER: minter_adm
            POSTGRES_PASSWORD: password
        volumes:
            - ./source/db_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 30s
            timeout: 3s
            retries: 5
    redis:
        container_name: "minter_explorer_cache"
        image: redis
        restart: always
        ports:
            - 6379:6379
    composer:
        container_name: "minter_explorer_composer"
        build: ./docker/composer
        volumes:
            - ./source:/app
        command: install